require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe Admin::ThemeAssetsController do
  
  #for actions
  let(:site) { mock_model(Site, :id => "1") }
  let(:current_user) { logged_in(:role? => "admin", :site_id => site.id) }
  let(:theme_asset) { mock_model("ThemeAsset", :site_id => site.id).as_null_object }
  
  before(:each) do
    cas_faker(current_user.puid)
    stub_c_site_c_user(site, current_user)
  end
  
  describe "GET index" do
    def do_get
      get :index
    end
    
    let(:theme_assets) { [theme_asset] }
    
    before(:each) do
      ThemeAsset.stub(:accessible_by).and_return(theme_assets)
    end
    
    it "should receive accessible_by" do
      ThemeAsset.should_receive(:accessible_by).and_return(theme_assets)
      do_get
    end
    
    it "should assign theme_assets for the view" do
      do_get
      assigns(:theme_assets).should == theme_assets
    end
    
    it "should render in the index template" do
      do_get
      response.should render_template("admin/theme_assets/index")
    end
    
  end
end